### ISSUE TITLE
ConvStackType.v3 in scripts/prediction_stepmania.py should be v7?

### ISSUE THREAD

**Issue by hongyu19930808** [KLab/AAAI-23.6040#2]
Also for notes_generator/prediction/onset_prediction.py: 
is_v3 = hasattr(model, "conv_stack_type") and model.conv_stack_type == ConvStackType.v3

since in /notes_generator/constants.py, there is no v3 version

**Comment by NaokiHamada** [comment]
Thanks for reporting!

`ConvStackType.v3` is an experimental version that only exists in our company's internal repo.
Since `is_v3` is not used in the public code, I will delete this statement.
